### ISSUE TITLE
Create REST API router

### ISSUE THREAD

**Issue by suzanamelomoraes** [horoeka-2019/Wa#19]
Write REST API - Routers

**Comment by marinatateoka** [comment]
By mistake all the commits related to getTasks written inside server.js and tasks.js has been done under #4 create database issue.
const sendGenericErrorMessage = (res) => {
  res.status(500).send(
    "An unexpected error has occurred and we're looking into it"
  )
}

router.get('/', (req, res) => {
  return db.getTasks()
    .then(tasks => res.json(tasks))
    .catch(() => sendGenericErrorMessage(res))
})

Code already reviewed by Andria
